version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: orgchart_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: orgchart
      POSTGRES_USER: orgchart_user
      POSTGRES_PASSWORD: orgchart_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tests/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orgchart_user -d orgchart"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: orgchart_pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@orgchart.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  default:
    name: orgchart_network
